# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = opacity 0.80 0.80, match:class ^(spotify)$, workspace 3 silent
windowrule = opacity 0.80 0.80, match:class ^(dolphin)$
windowrule = opacity 0.90 0.90, match:class ^(discord)$, workspace 1
windowrule = opacity 0.80 0.80, match:class ^(steam)$, workspace 3
windowrule = opacity 0.80 0.80, match:class ^(kitty)$
windowrule = opacity 0.80 0.80, match:class ^(kitty-dropterm)$
windowrule = opacity 0.80 0.80, match:class ^(bettersoundcloud)$, workspace 5 silent
windowrule = opacity 0.80 0.80, match:class ^(Termius)$
windowrule = float on, match:class ^(nwg-look)$
windowrule = float on, match:class ^(eog)$ #Imageviewer-Gtk
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$, size 750 550, move 1148 28
windowrule = float on, match:class ^(blueman-manager)$, move 1262 32
windowrule = float on, match:class ^(nm-applet)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(org.kde.polkit-kde-authentication-agent-1)$

# Steam
windowrule = float on, match:class ^(steam)$, match:title ^(Friends List)$
windowrule = stay_focused on, min_size 1 1, match:title ^()$, match:class ^(steam)$
windowrule = workspace 2 silent, match:class ^(steam_app_1476970)$


# Blur Rofi
#layerrule = blur on, animation popin, ignore_alpha 0, match:namespace rofi
#layerrule = blur on, ignore_alpha 0, match:namespace swaync-control-center
#layerrule = blur on, ignore_alpha 0, match:namespace swaync-notification-window

layerrule {
  name = noctalia
  match:namespace = noctalia-background-.*$
  ignore_alpha = 0.5
  blur = true
  blur_popups = true
}
