hl.on("hyprland.start", function()
    hl.exec_cmd("qs -c noctalia-shell")
    hl.exec_cmd("sleep 0.5 && qs -c noctalia-shell ipc call lockScreen lock")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("pypr")
    hl.exec_cmd("qs -c overview")
    hl.exec_cmd("[workspace special:magic silent] ~/dashboard.sh")
end)
